package presentation.utils

val String.Companion.selectOption get() = "Select an option: "
val String.Companion.exit get() = "0. Exit"
val String.Companion.welcomeMessage get() = "=== Welcome to PlanMate ==="
val String.Companion.mainMenu get() = "=== === Main Menu === ==="
val String.Companion.login get() = "1. Log in"
val String.Companion.logout get() = "0. Log out"
val String.Companion.goodbye get() = "Goodbye!"
val String.Companion.invalidOption get() = "Invalid option."
val String.Companion.selectionOne get() = "1"
val String.Companion.selectionZero get() = "0"
val String.Companion.selectionTwo get() = "2"
val String.Companion.selectionThree get() = "3"
val String.Companion.selectionFour get() = "4"
val String.Companion.selectionFive get() = "5"
val String.Companion.adminMenu get() = "=== Admin Menu ==="
val String.Companion.manageTasks get() = "1. Manage tasks"
val String.Companion.manageProjects get() = "2. Manage projects"
val String.Companion.manageUsers get() = "3. Manage users"
