package presentation.utils

val String.Companion.selectOption get() = "Select an option: "
val String.Companion.exit get() = "0. Exit"
val String.Companion.welcomeMessage get() = "=== Welcome to PlanMate ==="
val String.Companion.mainMenu get() = "=== === Main Menu === ==="
val String.Companion.login get() = "1. Log in"
val String.Companion.logout get() = "0. Log out"
val String.Companion.goodbye get() = "Goodbye!"
val String.Companion.invalidOption get() = "Invalid option."
val String.Companion.selectionOne get() = "1"
val String.Companion.selectionZero get() = "0"
val String.Companion.selectionTwo get() = "2"
val String.Companion.selectionThree get() = "3"
val String.Companion.selectionFour get() = "4"
val String.Companion.selectionFive get() = "5"
val String.Companion.mateMenu get() = "=== Mate Menu ==="
val String.Companion.viewTaskMenu get() = "1. View task menu"
val String.Companion.viewProjects get() = "2. View projects"
val String.Companion.adminMenu get() = "=== Admin Menu ==="
val String.Companion.manageTasks get() = "1. Manage tasks"
val String.Companion.manageProjects get() = "2. Manage projects"
val String.Companion.manageUsers get() = "3. Manage users"
val String.Companion.deleteUserStarted get() = "=== Delete user started ==="
val String.Companion.enterUserId get() = "Enter user id:"
val String.Companion.deletedSuccess get() = "Deleted Success"
val String.Companion.deletedFailed get() ="Deleted Failed"
val String.Companion.pressOneToTryAgain get() ="if you want to try again enter \"1\" else enter anything"
val String.Companion.manageUsersMenu get() ="=== Manage users menu ==="
val String.Companion.createNewUser get() ="1. Create new user"
val String.Companion.deleteUser get() ="2. Delete user"
val String.Companion.back get() = "0. Back"

val String.Companion.loginHeader get() = "=== Login ==="
val String.Companion.enterUserName get() = "Enter user name:"
val String.Companion.enterPassword get() = "Enter password:"
val String.Companion.loginSuccess get() = "Login Success"
val String.Companion.loginError get() = "Login error:("
val String.Companion.pleaseTryAgain get() = "Please try again:"