package presentation.utils

val String.Companion.selectOption get() = "Select an option: "
val String.Companion.exit get() = "0. Exit"
val String.Companion.welcomeMessage get() = "=== Welcome to PlanMate ==="
val String.Companion.mainMenu get() = "=== === Main Menu === ==="
val String.Companion.login get() = "1. Log in"
val String.Companion.logout get() = "0. Log out"
val String.Companion.goodbye get() = "Goodbye!"
val String.Companion.invalidOption get() = "Invalid option."
val String.Companion.selectionOne get() = "1"
val String.Companion.selectionZero get() = "0"
val String.Companion.selectionTwo get() = "2"
val String.Companion.selectionThree get() = "3"
val String.Companion.selectionFour get() = "4"
val String.Companion.selectionFive get() = "5"
val String.Companion.mateMenu get() = "=== Mate Menu ==="
val String.Companion.viewTaskMenu get() = "1. View task menu"
val String.Companion.viewProjects get() = "2. View projects"
val String.Companion.adminMenu get() = "=== Admin Menu ==="
val String.Companion.manageTasks get() = "1. Manage tasks"
val String.Companion.manageProjects get() = "2. Manage projects"
val String.Companion.manageUsers get() = "3. Manage users"
val String.Companion.deleteUserStarted get() = "=== Delete user started ==="
val String.Companion.enterUserId get() = "Enter user id:"
val String.Companion.deletedSuccess get() = "Deleted Success"
val String.Companion.deletedFailed get() = "Deleted Failed"
val String.Companion.pressOneToTryAgain get() = "if you want to try again enter \"1\" else enter anything"
val String.Companion.manageUsersMenu get() = "=== Manage users menu ==="
val String.Companion.createNewUser get() = "1. Create new user"
val String.Companion.deleteUser get() = "2. Delete user"
val String.Companion.back get() = "0. Back"
val String.Companion.taskMenuHeader get() = "=== Task Menu ==="
val String.Companion.createTask get() = "1. Create Task"
val String.Companion.editTask get() = "2. Edit Task"
val String.Companion.deleteTask get() = "3. Delete Task"
val String.Companion.displayAllTasksOption get() = "4. Display all tasks within a specific project"
val String.Companion.displayTaskLogs get() = "5. Display Task Audit Log by ID"
val String.Companion.displayAllTask get() = "=== Display All Tasks ==="
val String.Companion.enterProjectId get() = "Enter project ID: "
val String.Companion.enterTaskId get() = "Enter task ID: "
val String.Companion.enterNewTitle get() = "Enter new title: "
val String.Companion.enterNewDescription get() = "Enter new description: "
val String.Companion.empty get() = ""
val String.Companion.editTaskHeader get() = "=== Edit Task ==="
val String.Companion.taskUpdatedSuccessfully get() = "Task updated successfully"
val String.Companion.taskUpdatedUnsuccessfully get() = "Failed to update task"
val String.Companion.createTaskHeader get() = "=== Create Task ==="
val String.Companion.taskCreatedSuccessfully get() = "Task created successfully"
val String.Companion.taskCreatedUnsuccessfully get() = "Failed to create task"
val String.Companion.enterTaskTitle get() = "Enter task title: "
val String.Companion.enterTaskDescription get() = "Enter task description: "
val String.Companion.availableTaskStates get() = "Available task states:"
val String.Companion.selectTaskState get() = "Select task state: "


val String.Companion.projectMenuHeader get() = "=== Project Menu ==="
val String.Companion.displayProjects get() = "1. Display all projects"
val String.Companion.createProject get() = "2. Create Project"
val String.Companion.editProject get() = "3. Edit Project"
val String.Companion.deleteProject get() = "4. Delete Project"
val String.Companion.displayProjectLogs get() = "5. Display Projects Audit Log by ID"
val String.Companion.failedLoadProjects get() = "Failed to load projects:"
val String.Companion.noProjects get() = "No projects to display."
val String.Companion.projectsList get() = "=== Projects List ==="

val String.Companion.projectId get() = "ID"
val String.Companion.projectName get() = "Name"
val String.Companion.projectDescription get() = "Description"
val String.Companion.projectState get() = "Project State"
val String.Companion.createdBy get() = "Created By"
val String.Companion.projectLogs get() = "Project Logs"
val String.Companion.projectStates get() = "Project States"
val String.Companion.taskStates get() = "Task States"
val String.Companion.projectSeparator get() = "+--------------------------------------+"

val String.Companion.loginHeader get() = "=== Login ==="
val String.Companion.enterUserName get() = "Enter user name:"
val String.Companion.enterPassword get() = "Enter password:"
val String.Companion.loginSuccess get() = "Login Success"
val String.Companion.loginError get() = "Login error:("


val String.Companion.pleaseTryAgain get() = "Please try again:"


val String.Companion.projectAuditLogHeader get() = "=== Project Audit Log ==="
val String.Companion.enterProjectIDToViewAudit get() = "Enter Project ID to view audit logs: "

val String.Companion.taskAuditLogHeader get() = "=== Task Audit Log ==="
val String.Companion.enterTaskIdToViewLogs get() = "Enter Task ID to view audit logs: "
val String.Companion.taskLogNotFound get() = "No audit logs found for this task id : %s\n"
val String.Companion.auditLogsForTaskId get() = "Audit logs for task id: %s\n"
val String.Companion.auditLogsForProjectId get() = "Audit logs for project id: %s\n"
val String.Companion.auditLogException get() = "Failed to fetch audit logs : %s\n"


val String.Companion.deleteTaskHeader get() = "=== Delete Task ==="
val String.Companion.enterTaskIdToDelete get() = "Enter task ID to delete:"
val String.Companion.deleteTaskSuccess get() = "Task deleted successfully."
val String.Companion.deleteTaskException get() = "Failed to delete task : %s\n"


val String.Companion.deleteProjectHeader get() = "=== Delete Project ==="
val String.Companion.enterProjectIdToDelete get() = "Enter project ID to delete: "
val String.Companion.sureYouWantToDeleteThisProject get() = "Are you sure you want to delete this project? enter 1 to say yes: "
val String.Companion.deleteProjectSuccess get() = "Project deleted successfully."
val String.Companion.deletionCancelled get() = "Deletion cancelled."
val String.Companion.deleteProjectNotFoundException get() = "Project not found : %s\n"
val String.Companion.deleteProjectException get() = "Failed to delete project : %s\n"


val String.Companion.editProjectHeader get() = "=== Edit Project ==="
val String.Companion.enterProjectIdToEdit get() = "Enter the ID of the project to edit: "
val String.Companion.chooseFieldsEditProject get() = "Choose fields to edit\n1 - Name\n2 - Description\n3 - Project States\n4 - Finish"

val String.Companion.editProjectException get() = "\"Failed to edit project name: %s"
